variables:
  NODE_VERSION: 18

stages:
  - build
  - test
  - publish

before_script:
  - yarn install

typescript-compile:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - yarn compile
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/packages/commons/dist/
      - ${CI_PROJECT_DIR}/packages/generator/dist/
    expire_in: 1 hour

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - yarn test

publish-commons:
  stage: publish
  image: node:${NODE_VERSION}
  script:
    - cd ${CI_PROJECT_DIR}/packages/commons
    - npm version ${CI_COMMIT_TAG} --git-tag-version false
      --no-workspaces-update
    - yarn config set npmScopes.mittwald.npmAuthToken "${GITHUB_TOKEN}"
    - yarn npm publish
  only:
    - tags

update-client:
  stage: publish
  image: node:${NODE_VERSION}
  script:
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"
    - cd ${CI_PROJECT_DIR}/packages/mittwald
    - yarn generate:client
    - git status
    - |
      if [ $(git status --porcelain . | wc -l) -gt 0 ] ; then
        cd ${CI_PROJECT_DIR}
        yarn compile

        cd ${CI_PROJECT_DIR}/packages/mittwald

        # TODO: Re-enable as soon as we have a stability guarantee
        # npm version --no-workspaces-update --no-git-tag-version patch
      
        npm version --no-workspaces-update --no-git-tag-version --preid alpha prerelease

        git add .
        git commit -m "Update generated client";
        
        git push "https://project:${PAT}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_BRANCH}"

        yarn config set npmScopes.mittwald.npmAuthToken "${GITHUB_TOKEN}"
        yarn npm publish
      fi
  only:
    - schedules
    - web
