variables:
  NODE_VERSION: 18

before_script:
  - npm config set @mittwald:registry https://npm.pkg.github.com/ -Luser
  - npm config set //npm.pkg.github.com/:_authToken "${GITHUB_TOKEN}" -Luser
  - yarn install

typescript-compile:
  image: node:${NODE_VERSION}
  script:
    - yarn compile
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/packages/commons/dist/
      - ${CI_PROJECT_DIR}/packages/generator/dist/
    expire_in: 1 hour

test:
  image: node:${NODE_VERSION}
  needs:
    - typescript-compile
  script:
    - yarn test

publish-commons:
  image: node:${NODE_VERSION}
  needs:
    - test
  script:
    - cd ${CI_PROJECT_DIR}/packages/commons
    - npm version ${CI_COMMIT_TAG} --git-tag-version false
      --no-workspaces-update
    - npm publish
  only:
    - tags

generate-client:
  image: node:${NODE_VERSION}
  needs:
    - test
  script:
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"
    - cd ${CI_PROJECT_DIR}/packages/mittwald
    - yarn generate:client
    - git status
    - |
      if [ $(git status --porcelain . | wc -l) -gt 0 ] ; then
        cd ${CI_PROJECT_DIR}
        yarn compile

        cd ${CI_PROJECT_DIR}/packages/mittwald

        npm version --no-workspaces-update --no-git-tag-version patch

        git add .
        git commit -m "Update generated client";
        
        git push "https://project:${PAT}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_BRANCH}"

        yarn npm publish
      fi
  only:
    - schedules
    - web
