include:
  - packages/api-client/.gitlab-ci.yml
  - packages/openapi-to-typescript/.gitlab-ci.yml
stages:
  - compile
  - test
  - publish
test:project-base-up-to-date:
  image: gitlab-registry.mittwald.it/coab-0x7e7/tools/go-dev-env
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  tags:
    - dockermultistage
  script:
    - ${CI_PROJECT_DIR}/.scripts/project-base-update-recursive.sh
    - git diff --exit-code
  except:
    - tags
  allow_failure: true
compile:all:
  extends: .npm-install
  image: node:${NODE_VERSION}
  stage: compile
  tags:
    - dockermultistage
  script:
    - yarn workspaces run compile
  interruptible: true
  artifacts:
    paths:
      - packages/api-client/dist/
      - packages/openapi-to-typescript/dist/
    expire_in: 1 hour
