compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  mittwald:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.mittwald.it"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
