compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: false

nodeLinker: pnp

npmMinimalAgeGate: 10080 # 1 week in minutes
npmPreapprovedPackages:
  - "@mittwald/*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
