variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/openapi-to-typescript:$CI_COMMIT_TAG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE/openapi-to-typescript:latest
  IMAGE_TAG_STABLE: $CI_REGISTRY_IMAGE/openapi-to-typescript:stable
  DOCKERFILE: ./openapi-to-typescript/Dockerfile

.test:dockerbuild:
  image: docker
  tags:
    - dockermultistage
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -f "${DOCKERFILE}" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" -t "${IMAGE_TAG_LATEST}" .
  except:
    - tags

.publish:dev:docker:
  image: docker
  tags:
    - dockermultistage
  before_script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  script:
    - docker build -f "${DOCKERFILE}" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" -t "${IMAGE_TAG_LATEST}" .
    - docker push "${IMAGE_TAG_LATEST}"
  only:
    - master
  except:
    - tags

.publish:docker:
  tags:
    - dockermultistage
  image: docker
  before_script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  script:
    - docker build -f "${DOCKERFILE}" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" -t "${IMAGE_TAG_STABLE}" .
    - docker tag "${IMAGE_TAG_STABLE}" "${IMAGE_TAG}"
    - docker push "${IMAGE_TAG_STABLE}"
    - docker push "${IMAGE_TAG}"
  only:
    - tags
