variables:
  SENTRY_RELEASE: ${CI_PROJECT_NAME}@${CI_COMMIT_TAG}

.sentry:release:
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases new -p "${CI_PROJECT_NAME}" --finalize "${SENTRY_RELEASE}"
    - sentry-cli releases set-commits --auto "${SENTRY_RELEASE}"

.sentry:deploy:prod:
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases deploys "${SENTRY_RELEASE}" new -e production
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){2,3}$/'
      when: on_success

.sentry:deploy:dev:
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases deploys "${SENTRY_RELEASE}" new -e development
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){2,3}(-.+)?$/'
      when: on_success
